/* Abu Shreek student accounts via Supabase Auth. Existing study features stay untouched. */
(function(){
const cfg=window.ABU_AUTH_CONFIG||{};let sb=null;
const levels=['الصف التاسع','بكالوريا علمي','بكالوريا أدبي'];
function el(t,a={},h=''){const x=document.createElement(t);Object.entries(a).forEach(([k,v])=>k==='class'?x.className=v:x.setAttribute(k,v));x.innerHTML=h;return x}
function injectStyle(){if(document.getElementById('abuAuthStyle'))return;const s=el('style',{id:'abuAuthStyle'});s.textContent=`#abuAuthOverlay{position:fixed;inset:0;background:#f4f8f7;z-index:20000;display:flex;align-items:center;justify-content:center;padding:18px;direction:rtl}.abu-auth-box{width:min(460px,100%);background:#fff;border:1px solid #dce8e5;border-radius:24px;padding:24px;box-shadow:0 18px 60px #0002}.abu-auth-box h1,.abu-auth-box h2{margin:0 0 8px}.abu-auth-box input,.abu-auth-box select{width:100%;box-sizing:border-box;padding:12px;margin:6px 0 10px;border:1px solid #cbd5e1;border-radius:12px;font:inherit}.abu-auth-tabs{display:flex;gap:8px;margin:14px 0}.abu-auth-tabs button{flex:1}.abu-auth-msg{min-height:24px;font-size:14px;margin-top:8px}.abu-profile-btn{position:fixed;left:16px;bottom:16px;z-index:9000;border-radius:999px!important}.abu-auth-hidden{display:none!important}`;document.head.appendChild(s)}
function msg(t,bad=false){const m=document.getElementById('abuAuthMsg');if(m){m.textContent=t;m.style.color=bad?'#b91c1c':'#166534'}}
function setup(){injectStyle();if(!cfg.url||!cfg.anonKey){console.warn('ABU_AUTH_CONFIG missing');return}if(!window.supabase){console.error('Supabase client missing');return}sb=window.supabase.createClient(cfg.url,cfg.anonKey);render();sb.auth.onAuthStateChange(()=>refresh())}
function render(){if(document.getElementById('abuAuthOverlay'))return;const o=el('div',{id:'abuAuthOverlay'});o.innerHTML=`<div class="abu-auth-box"><h1>🎓 أبو شريك</h1><p>سجّل الدخول إلى حسابك لمتابعة دراستك.</p><div class="abu-auth-tabs"><button class="btn primary" id="abuLoginTab">تسجيل الدخول</button><button class="btn soft" id="abuSignupTab">إنشاء حساب</button></div><form id="abuAuthForm"><div id="abuNameWrap" class="abu-auth-hidden"><label>الاسم أو الاسم المستعار</label><input id="abuName" maxlength="50" autocomplete="name"></div><div id="abuLevelWrap" class="abu-auth-hidden"><label>المرحلة الدراسية</label><select id="abuLevel">${levels.map(x=>`<option>${x}</option>`).join('')}</select></div><label>البريد الإلكتروني</label><input id="abuEmail" type="email" required autocomplete="email"><label>كلمة المرور</label><input id="abuPassword" type="password" minlength="8" required autocomplete="current-password"><button class="btn primary" style="width:100%;margin-top:8px" id="abuSubmit">دخول</button><div id="abuAuthMsg" class="abu-auth-msg"></div></form></div>`;document.body.appendChild(o);let mode='login';const setMode=m=>{mode=m;document.getElementById('abuNameWrap').classList.toggle('abu-auth-hidden',m==='login');document.getElementById('abuLevelWrap').classList.toggle('abu-auth-hidden',m==='login');document.getElementById('abuSubmit').textContent=m==='login'?'دخول':'إنشاء الحساب';document.getElementById('abuPassword').autocomplete=m==='login'?'current-password':'new-password';msg('')};document.getElementById('abuLoginTab').onclick=()=>setMode('login');document.getElementById('abuSignupTab').onclick=()=>setMode('signup');document.getElementById('abuAuthForm').onsubmit=async e=>{e.preventDefault();const email=document.getElementById('abuEmail').value.trim(),password=document.getElementById('abuPassword').value;if(mode==='signup'){const name=document.getElementById('abuName').value.trim(),level=document.getElementById('abuLevel').value;if(!name)return msg('اكتب اسمك أو اسماً مستعاراً.',true);const {data,error}=await sb.auth.signUp({email,password,options:{data:{display_name:name,study_level:level}}});if(error)return msg(error.message,true);if(!data.session)return msg('تم إنشاء الحساب. تحقق من بريدك الإلكتروني لتأكيد الحساب.');return refresh()}const {error}=await sb.auth.signInWithPassword({email,password});if(error)return msg('البريد الإلكتروني أو كلمة المرور غير صحيحة.',true);refresh()};refresh()}
async function refresh(){if(!sb)return;const {data}=await sb.auth.getUser();const u=data.user,o=document.getElementById('abuAuthOverlay');if(!u){if(o)o.classList.remove('abu-auth-hidden');document.getElementById('abuProfileBtn')?.remove();return}if(o)o.classList.add('abu-auth-hidden');let b=document.getElementById('abuProfileBtn');if(!b){b=el('button',{id:'abuProfileBtn',class:'btn primary abu-profile-btn'},'👤 حسابي');b.onclick=()=>profile(u);document.body.appendChild(b)}const md=u.user_metadata||{};b.textContent=`👤 ${md.display_name||'حسابي'}`}
function profile(u){document.getElementById('abuProfileModal')?.remove();const md=u.user_metadata||{},d=el('div',{id:'abuProfileModal'});d.style.cssText='position:fixed;inset:0;background:#0006;z-index:21000;display:flex;align-items:center;justify-content:center;padding:18px;direction:rtl';d.innerHTML=`<div class="abu-auth-box"><h2>👤 حسابي</h2><label>الاسم</label><input id="abuEditName" value="${String(md.display_name||'').replace(/"/g,'&quot;')}"><label>المرحلة</label><select id="abuEditLevel">${levels.map(x=>`<option ${x===md.study_level?'selected':''}>${x}</option>`).join('')}</select><p style="font-size:14px">${u.email||''}</p><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn primary" id="abuSaveProfile">حفظ</button><button class="btn soft" id="abuLogout">تسجيل الخروج</button><button class="btn soft" id="abuCloseProfile">إغلاق</button></div><div id="abuProfileMsg" class="abu-auth-msg"></div></div>`;document.body.appendChild(d);document.getElementById('abuCloseProfile').onclick=()=>d.remove();document.getElementById('abuLogout').onclick=async()=>{await sb.auth.signOut();d.remove();refresh()};document.getElementById('abuSaveProfile').onclick=async()=>{const display_name=document.getElementById('abuEditName').value.trim(),study_level=document.getElementById('abuEditLevel').value;const {error}=await sb.auth.updateUser({data:{display_name,study_level}});document.getElementById('abuProfileMsg').textContent=error?error.message:'تم حفظ الملف الشخصي.';if(!error)refresh()}}
window.addEventListener('DOMContentLoaded',setup);if(document.readyState!=='loading')setup();
})();