/* دليل ما بعد البكالوريا - الجامعات السورية فقط */
(function(){
const tracks={
 scientific:{title:'🔬 البكالوريا العلمي',desc:'استكشف الاختصاصات المتاحة بعد الفرع العلمي في الجامعات السورية.',groups:[
 ['🩺 الطب والعلوم الصحية','الطب البشري، طب الأسنان، الصيدلة، العلوم الصحية، التمريض، المعالجة الفيزيائية، المخابر والتغذية.','طبيب، طبيب أسنان، صيدلي، مختص مخبري أو صحي، علاج فيزيائي وتمريض.','جامعة دمشق، جامعة حلب، جامعة اللاذقية، جامعة حمص، جامعة الفرات، إضافة إلى جامعات سورية خاصة بحسب الاختصاص.'],
 ['⚙️ الهندسات','الهندسة المدنية، المعمارية، المعلوماتية، الميكانيكية، الكهربائية، الميكاترونكس، الكيميائية، الزراعية، البترول والطاقة وغيرها.','مهندس تصميم أو تنفيذ أو إنتاج، برمجيات وتقنية معلومات، طاقة، اتصالات، صناعة وبنية تحتية بحسب الفرع.','جامعة دمشق، جامعة حلب، جامعة اللاذقية، جامعة حمص، جامعة الفرات، جامعة حماة، جامعة طرطوس، جامعة إدلب وجامعات سورية خاصة بحسب الاختصاص.'],
 ['💻 المعلوماتية والتقانات','الهندسة المعلوماتية، هندسة البرمجيات، الذكاء الاصطناعي وعلوم البيانات، الأمن السيبراني، الحاسوب وتقانات المعلومات.','تطوير البرمجيات، تحليل البيانات، الذكاء الاصطناعي، الشبكات، الأمن السيبراني ونظم المعلومات.','تتوفر هذه المجالات في عدد من الجامعات الحكومية والخاصة السورية، ويختلف اسم البرنامج من جامعة إلى أخرى.'],
 ['🧪 العلوم الأساسية','الرياضيات، الفيزياء، الكيمياء، الجيولوجيا، الإحصاء، علوم الحياة والعلوم البيئية.','البحث العلمي، المختبرات، التعليم، التحليل والقطاعات الصناعية والبيئية بحسب الاختصاص.','جامعة دمشق وعدد من الجامعات الحكومية السورية الأخرى، وبعض الجامعات الخاصة بحسب البرنامج.'],
 ['🌱 الزراعة والبيئة','الهندسة الزراعية، تقانة الغذاء، البيئة والتنمية المستدامة وبعض التخصصات الحيوية.','الإنتاج الزراعي، الصناعات الغذائية، الجودة، البيئة والبحث والتطوير.','متاحة في عدة جامعات سورية حكومية وبعض الجامعات الخاصة.'],
 ['📊 الاقتصاد والإدارة','الاقتصاد، إدارة الأعمال، المحاسبة، التمويل والمصارف وريادة الأعمال وفق شروط القبول.','الإدارة، المحاسبة، المصارف، التمويل، التسويق وإدارة المشاريع.','جامعة دمشق وجامعات حكومية وخاصة سورية متعددة.']
 ]},
 literary:{title:'📚 البكالوريا الأدبي',desc:'استكشف الاختصاصات الأدبية والإنسانية والإدارية المتاحة في الجامعات السورية.',groups:[
 ['🗣️ اللغات والآداب','اللغة العربية، الإنكليزية، الفرنسية، الروسية ولغات وآداب أخرى بحسب الجامعة.','التعليم، الترجمة، التحرير، المحتوى، العلاقات الثقافية وأعمال تستخدم اللغات.','جامعة دمشق وجامعات حكومية سورية أخرى، وبعض الجامعات الخاصة.'],
 ['⚖️ الحقوق والعلوم السياسية','الحقوق، القانون والعلوم السياسية وفق شروط كل برنامج.','المحاماة بعد استيفاء المتطلبات المهنية، الأعمال القانونية، الإدارة والمؤسسات والبحث السياسي.','جامعة دمشق وعدد من الجامعات الحكومية والخاصة السورية.'],
 ['📊 الاقتصاد والإدارة','الاقتصاد، إدارة الأعمال، المحاسبة، التمويل والمصارف والعلوم الإدارية وفق شروط القبول.','الإدارة، المحاسبة، المصارف، التسويق، الموارد البشرية وإدارة المشاريع.','جامعة دمشق وجامعات حكومية وخاصة سورية متعددة.'],
 ['🧠 العلوم الإنسانية والتربية','علم النفس، علم الاجتماع، الإرشاد النفسي، التربية، معلم الصف، تربية الطفل والتربية الخاصة.','التعليم والإرشاد والعمل الاجتماعي والتربوي والمؤسسات المجتمعية بحسب الاختصاص ومتطلبات المهنة.','جامعة دمشق وعدد من الجامعات الحكومية والخاصة السورية.'],
 ['🏺 التاريخ والجغرافيا والآثار والفلسفة','التاريخ، الجغرافيا، الآثار، الفلسفة والمكتبات والمعلومات.','التعليم، البحث، المتاحف والتراث، الأرشفة والمكتبات ومجالات ثقافية وإدارية.','جامعة دمشق وجامعات حكومية سورية أخرى بحسب الاختصاص.'],
 ['🎙️ الإعلام والفنون والسياحة','الإعلام، السياحة وبعض تخصصات الفنون والتصميم وفق شروط القبول والاختبارات المطلوبة إن وجدت.','الصحافة والإعلام الرقمي، العلاقات العامة، السياحة، التصميم والفنون بحسب التخصص.','جامعة دمشق وعدد من الجامعات السورية الحكومية والخاصة بحسب البرنامج.']
 ]}
};
function style(){if(document.getElementById('futureStyle'))return;const s=document.createElement('style');s.id='futureStyle';s.textContent=`.future-head{margin:30px 0 14px}.future-card{grid-column:1/-1;background:linear-gradient(135deg,#fff,#edf9f6);border:1px solid var(--line);border-radius:20px;padding:25px;cursor:pointer;display:flex;align-items:center;gap:18px;transition:.2s}.future-card:hover,.future-option:hover,.major-card:hover{border-color:var(--g2);transform:translateY(-2px)}.future-card .icon{font-size:48px}.future-options{display:grid;grid-template-columns:repeat(2,1fr);gap:20px;margin-top:28px}.future-option,.major-card{background:#fff;border:1px solid var(--line);border-radius:20px;padding:24px;cursor:pointer;transition:.2s}.future-option .icon{font-size:44px}.major-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.major-card h3{margin:0 0 10px}.major-detail{background:#fff;border:1px solid var(--line);border-radius:20px;padding:25px}.info-box{background:#f7faf9;border-radius:14px;padding:16px;margin:12px 0}.future-source{margin-top:22px;padding:14px;background:#edf9f6;border-radius:14px;color:var(--muted);font-size:13px}@media(max-width:760px){.future-options,.major-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function sections(){if(document.getElementById('future'))return;const main=document.querySelector('main');main.insertAdjacentHTML('beforeend',`<section id="future" class="hidden"><div class="topbar"><button class="btn soft" onclick="show('home')">← الرئيسية</button><h2>🎓 مستقبلك بعد البكالوريا</h2></div><div class="hero" style="padding:20px 0"><h1 style="font-size:32px">ماذا تريد أن تدرس بعد البكالوريا؟</h1><p>دليل مبسط للاختصاصات والجامعات الموجودة داخل سوريا فقط.</p></div><div class="future-options"><div class="future-option" onclick="openFutureTrack('scientific')"><div class="icon">🔬</div><h2>البكالوريا العلمي</h2><p class="note">الطب، الهندسات، المعلوماتية، العلوم وغيرها.</p></div><div class="future-option" onclick="openFutureTrack('literary')"><div class="icon">📚</div><h2>البكالوريا الأدبي</h2><p class="note">اللغات، الحقوق، الاقتصاد، العلوم الإنسانية وغيرها.</p></div></div></section><section id="futureTrack" class="hidden"><div class="topbar"><button class="btn soft" onclick="show('future')">← الفرعين</button><h2 id="futureTrackTitle"></h2></div><p id="futureTrackDesc" class="note"></p><div id="majorGrid" class="major-grid"></div><div class="future-source">ملاحظة: أسماء البرامج وشروط القبول والمفاضلة قد تتغير من عام إلى آخر. لذلك يجب التأكد من إعلان المفاضلة الرسمي للعام الدراسي الحالي قبل التسجيل.</div></section><section id="majorDetail" class="hidden"><div class="topbar"><button class="btn soft" onclick="show('futureTrack')">← الاختصاصات</button><h2 id="majorTitle"></h2></div><div class="major-detail"><div class="info-box"><h3>📖 ماذا تدرس؟</h3><p id="majorStudy"></p></div><div class="info-box"><h3>💼 ماذا يمكن أن تعمل بعد التخرج؟</h3><p id="majorJobs"></p></div><div class="info-box"><h3>🏛️ أين يمكن دراسة هذا المجال في سوريا؟</h3><p id="majorUniversities"></p></div><p class="note">هذه مقدمة إرشادية وليست قرار قبول. توفر الاختصاص وشروطه يجب التحقق منهما حسب مفاضلة السنة والجامعة.</p></div></section>`)}
function homeCard(){const g=document.querySelector('#home .grid');if(!g||document.getElementById('futureHomeCard'))return;const d=document.createElement('div');d.id='futureHomeCard';d.className='future-card';d.onclick=()=>show('future');d.innerHTML='<div class="icon">🎓</div><div><h2>مستقبلك بعد البكالوريا</h2><p>تعرّف على الاختصاصات، مجالات العمل، وأين يمكنك دراستها في الجامعات السورية.</p><b style="color:var(--g)">علمي أو أدبي ←</b></div>';g.appendChild(d)}
window.openFutureTrack=function(k){const t=tracks[k];futureTrackTitle.textContent=t.title;futureTrackDesc.textContent=t.desc;majorGrid.innerHTML='';t.groups.forEach((m,i)=>{const d=document.createElement('div');d.className='major-card';d.innerHTML=`<h3>${m[0]}</h3><p class="note">${m[1]}</p><span style="color:var(--g);font-weight:700">اعرف أكثر ←</span>`;d.onclick=()=>openMajor(k,i);majorGrid.appendChild(d)});show('futureTrack')};
window.openMajor=function(k,i){const m=tracks[k].groups[i];majorTitle.textContent=m[0];majorStudy.textContent=m[1];majorJobs.textContent=m[2];majorUniversities.textContent=m[3];show('majorDetail')};
style();sections();homeCard();
})();