import http from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import { extname, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';
const root=fileURLToPath(new URL('.',import.meta.url));
const PORT=Number(process.env.PORT||3000);
const OLLAMA_URL='http://127.0.0.1:11434';
const MODEL=process.env.OLLAMA_MODEL||'qwen2.5:3b-instruct-q5_K_S';
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.pdf':'application/pdf','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.svg':'image/svg+xml'};
function send(res,status,body,type='application/json; charset=utf-8'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store'});res.end(typeof body==='string'?body:JSON.stringify(body));}
function readBody(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>resolve(s));req.on('error',reject);});}
async function askOllama(prompt,json=false){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),90000);try{const r=await fetch(`${OLLAMA_URL}/api/generate`,{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({model:MODEL,prompt,stream:false,think:false,...(json?{format:'json'}:{}),options:{temperature:json?0.1:0.3,num_predict:json?1200:420,repeat_penalty:1.18,repeat_last_n:128}})});const raw=await r.text();let j={};try{j=JSON.parse(raw)}catch{}if(!r.ok)throw new Error(j.error||raw||`Ollama HTTP ${r.status}`);const answer=String(j.response||'').trim();if(!answer)throw new Error('Ollama أعاد إجابة فارغة.');return answer;}finally{clearTimeout(timer);}}
function source(data){return String(data.sourceText||data.pageText||'').trim().slice(0,18000)}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');
if(req.method==='GET'&&url.pathname==='/api/status'){try{const r=await fetch(`${OLLAMA_URL}/api/tags`);const j=await r.json();return send(res,r.ok?200:503,{ok:r.ok,model:MODEL,models:j.models||[]});}catch{return send(res,503,{ok:false,error:'Ollama غير مشغّل.'});}}
if(req.method==='POST'&&url.pathname==='/api/ask'){const data=JSON.parse(await readBody(req)||'{}');const question=String(data.question||'').trim();if(!question)return send(res,400,{error:'السؤال فارغ.'});const text=source(data);const prompt=`أنت مساعد تعليمي لمنصة أبو شريك. أجب بالعربية فقط وبمستوى الطالب. المستوى: ${data.level||'غير محدد'}. المادة: ${data.book||'غير محددة'}. الصفحة: ${data.page||'غير محددة'}.\nالمصدر المتاح:\n${text||'[لا يوجد نص مصدر متاح]'}\nلا تدّع أنك قرأت شيئاً غير موجود في المصدر. إذا كان السؤال عن محتوى الصفحة ولا يكفي النص المتاح، قل بوضوح إنك تحتاج نصاً أو صورة الجزء المطلوب.\nسؤال الطالب: ${question}\nالجواب:`;try{return send(res,200,{answer:await askOllama(prompt)});}catch(e){return send(res,503,{error:e.name==='AbortError'?'تأخر الذكاء الاصطناعي أكثر من 90 ثانية.':String(e.message||e)});}}
if(req.method==='POST'&&url.pathname==='/api/study'){const data=JSON.parse(await readBody(req)||'{}');const text=source(data);if(text.length<80)return send(res,400,{error:'لا يوجد نص كافٍ من الكتاب لإنشاء محتوى موثوق. افتح صفحات الكتاب أولاً أو أضف نص المادة.'});const mode=data.mode==='mcq'?'mcq':'cards';const rules=mode==='cards'?`أنشئ من المصدر فقط 8 بطاقات تعليمية مفيدة وغير مكررة. أعد JSON فقط بالشكل: {"items":[{"front":"سؤال قصير","back":"جواب دقيق من المصدر"}]}. لا تضف معلومات من خارج المصدر.`:`أنشئ من المصدر فقط 8 أسئلة اختيار من متعدد مفيدة وغير مكررة. لكل سؤال أربع إجابات مع إجابة صحيحة واحدة. أعد JSON فقط بالشكل: {"items":[{"question":"السؤال","options":["أ","ب","ج","د"],"answer":0,"explanation":"سبب مختصر من المصدر"}]}. غيّر موضع الإجابة الصحيحة بين الأسئلة ولا تستخدم أسئلة سطحية عن رقم الصفحة أو لون الكتاب.`;const prompt=`أنت منشئ محتوى دراسي لمنصة أبو شريك. المستوى: ${data.level||''}. المادة: ${data.book||''}.\n${rules}\nالمصدر:\n${text}`;try{const raw=await askOllama(prompt,true);let parsed;try{parsed=JSON.parse(raw)}catch{return send(res,502,{error:'تعذر قراءة المحتوى المولد.'});}return send(res,200,parsed);}catch(e){return send(res,503,{error:String(e.message||e)});}}
if(req.method!=='GET')return send(res,405,{error:'Method not allowed'});let pathname=decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname);const safe=normalize(pathname).replace(/^[/\\]+/,'').replace(/^(\.\.(\/|\\|$))+/,'');const path=join(root,safe);if(!path.startsWith(root))return send(res,403,'Forbidden','text/plain');try{const st=await stat(path);if(!st.isFile())throw new Error();const file=await readFile(path);res.writeHead(200,{'Content-Type':types[extname(path).toLowerCase()]||'application/octet-stream','Cache-Control':'no-store, no-cache, must-revalidate'});res.end(file);}catch{return send(res,404,'Not found','text/plain');}}catch(e){console.error('[Server]',e);send(res,500,{error:String(e.message||e)});}});
server.listen(PORT,()=>console.log(`أبو شريك يعمل على http://localhost:${PORT} — ${MODEL}`));