import http from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import { extname, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Readable } from 'node:stream';
const root=fileURLToPath(new URL('.',import.meta.url));
const PORT=Number(process.env.PORT||3000);
const GEMINI_API_KEY=process.env.GEMINI_API_KEY||'';
const MODEL=process.env.GEMINI_MODEL||'gemini-3.5-flash-lite';
const FALLBACK_MODELS=['gemini-3.5-flash-lite','gemini-3.8-flash'];
const AI_TIMEOUT_MS=Number(process.env.AI_TIMEOUT_MS||110000);
const RELEASE_BASE='https://github.com/ahmadaljarad/abu-shreek/releases/download/books-v1/';
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.pdf':'application/pdf','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.svg':'image/svg+xml'};
function send(res,status,body,type='application/json; charset=utf-8'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store'});res.end(typeof body==='string'?body:JSON.stringify(body));}
function readBody(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>250000){reject(new Error('request too large'));req.destroy();}});req.on('end',()=>resolve(s));req.on('error',reject);});}
async function askOne(model,prompt,json=false){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),AI_TIMEOUT_MS);try{const endpoint=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(GEMINI_API_KEY)}`;const body={contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{temperature:json?0.15:0.3,maxOutputTokens:json?1400:700,...(json?{responseMimeType:'application/json'}:{})}};const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify(body)});const raw=await r.text();let j={};try{j=JSON.parse(raw)}catch{}if(!r.ok){const e=new Error(j?.error?.message||raw||`Gemini HTTP ${r.status}`);e.status=r.status;throw e;}const answer=(j.candidates?.[0]?.content?.parts||[]).map(p=>p.text||'').join('').trim();if(!answer)throw new Error('empty response');return answer;}finally{clearTimeout(timer);}}
async function askAI(prompt,json=false){if(!GEMINI_API_KEY)throw Object.assign(new Error('GEMINI_API_KEY غير مضبوط على Render.'),{code:'NO_KEY'});let last;for(const model of [...new Set([MODEL,...FALLBACK_MODELS])]){try{const answer=await askOne(model,prompt,json);console.log('[AI OK]',model);return answer;}catch(e){last=e;console.error('[AI FAIL]',model,e.status||'',e.message);if(e.status===400||e.status===401||e.status===403)break;}}throw last||new Error('AI unavailable');}
function friendlyError(e){const s=String(e?.message||e||'');if(e?.code==='NO_KEY')return 'مفتاح الذكاء الاصطناعي غير مضبوط على الخادم.';if(e?.name==='AbortError'||/aborted/i.test(s))return 'استغرق الذكاء الاصطناعي وقتاً أطول من المتوقع. حاول مرة أخرى.';if(/API key|invalid key|permission|403|401/i.test(s))return 'مفتاح Gemini غير صالح أو لا يملك الصلاحية. تحقق من GEMINI_API_KEY في Render.';if(/not found|not supported|model/i.test(s)&&/404|not found|supported/i.test(s))return 'نموذج الذكاء الاصطناعي غير متاح لهذا المفتاح.';if(/high demand|overloaded|resource exhausted|quota|429|503|unavailable/i.test(s))return 'خدمة الذكاء الاصطناعي مشغولة أو تجاوزت الحصة حالياً. جرّب مرة أخرى بعد قليل.';return 'تعذر الحصول على إجابة من الذكاء الاصطناعي حالياً. تحقق من سجل الخادم.';}
function source(data){return String(data.sourceText||data.pageText||'').trim().slice(0,7000)}
function studyPolicy(book=''){return `هدفك إعداد الطالب للدرس والامتحان، وليس تحويل كل سطر في الصفحة إلى سؤال. المادة/الكتاب: ${book||'غير محدد'}.
قواعد إلزامية:
- استخدم فقط المعلومات التعليمية الفعلية الموجودة في المصدر المرسل، ولا تخترع معلومة غير موجودة فيه.
- تجاهل تماماً الغلاف، حقوق التأليف والنشر، اسم الوزارة أو المؤسسة أو دار الطباعة والنشر، أرقام الإيداع والطبعة، أسماء المؤلفين والمراجعين، بيانات الطباعة، المقدمة الإدارية، الفهرس، رقم الصفحة، رؤوس وتذييلات الصفحات، والشعارات، إلا إذا كانت هذه المعلومة نفسها موضوع الدرس.
- لا تسأل أبداً: لمن تعود حقوق النشر؟ من الناشر؟ ما اسم الوزارة؟ من ألّف الكتاب؟ ما رقم الطبعة؟ أو أي سؤال إداري مشابه.
- اختر أهم الأفكار التي يحتاج الطالب إلى فهمها أو حفظها ويمكن أن تظهر في اختبار مدرسي.
- تجنب الأسئلة التافهة أو التي يمكن جوابها بمجرد قراءة عنوان الصفحة.
- نوّع مستوى الأسئلة: تعريف وفهم، سبب ونتيجة، مقارنة أو استنتاج أو تطبيق عندما يسمح المصدر بذلك.
- للتاريخ والتربية الوطنية: ركز على الأحداث والتواريخ والشخصيات والأسباب والنتائج والأهمية والعلاقات بينها.
- للجغرافيا: ركز على المفاهيم والمواقع والخصائص والأسباب والنتائج والمقارنات والعلاقات.
- للعلوم والفيزياء والكيمياء والرياضيات: ركز على المفاهيم والقوانين والرموز والوحدات والتجارب والخطوات والاستنتاج والتطبيق، ولا تسأل عن معلومات شكلية.
- للعربية واللغات: ركز على المعنى والفكرة والقواعد والمفردات والأساليب والاستيعاب بحسب النص.
- للتربية الدينية: ركز على المعاني والمفاهيم والأحكام والقيم والاستدلال الموجود في النص.
- إذا كان المصدر لا يحتوي مادة تعليمية كافية (مثلاً غلاف أو صفحة حقوق نشر فقط)، لا تولّد أسئلة رديئة. أعد items فارغة.`;}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');
if(req.method==='GET'&&url.pathname==='/api/status'){if(!GEMINI_API_KEY)return send(res,503,{ok:false,provider:'Gemini',model:MODEL,error:'GEMINI_API_KEY غير مضبوط.'});try{const answer=await askAI('أجب بكلمة واحدة فقط: جاهز');return send(res,200,{ok:true,provider:'Gemini',model:MODEL,test:answer});}catch(e){return send(res,503,{ok:false,provider:'Gemini',model:MODEL,error:friendlyError(e),detail:String(e?.message||e).slice(0,500)});}}
if(req.method==='GET'&&url.pathname==='/api/book'){const file=String(url.searchParams.get('file')||'');if(!/^[A-Za-z0-9._-]+\.pdf$/i.test(file))return send(res,400,{error:'اسم ملف الكتاب غير صالح.'});try{const headers={'User-Agent':'Abu-Shreek/1.0','Accept':'application/pdf,application/octet-stream;q=0.9,*/*;q=0.8'};if(req.headers.range)headers.Range=req.headers.range;const upstream=await fetch(RELEASE_BASE+encodeURIComponent(file),{redirect:'follow',headers});if(!upstream.ok&&upstream.status!==206)return send(res,upstream.status===404?404:502,{error:`تعذر تحميل الكتاب من المصدر (${upstream.status}).`});if(!upstream.body)return send(res,502,{error:'تعذر تحميل ملف الكتاب حالياً.'});const outHeaders={'Content-Type':upstream.headers.get('content-type')||'application/pdf','Cache-Control':'public, max-age=3600','Access-Control-Allow-Origin':'*','Accept-Ranges':upstream.headers.get('accept-ranges')||'bytes'};for(const h of ['content-length','content-range','etag','last-modified']){const v=upstream.headers.get(h);if(v)outHeaders[h]=v;}res.writeHead(upstream.status===206?206:200,outHeaders);const stream=Readable.fromWeb(upstream.body);req.on('close',()=>{if(!stream.destroyed)stream.destroy();});stream.on('error',e=>{console.error('[Book stream]',e);if(!res.headersSent)send(res,502,{error:'انقطع تحميل الكتاب. حاول مرة أخرى.'});else res.destroy(e);});stream.pipe(res);return;}catch(e){console.error('[Book proxy]',e);if(!res.headersSent)return send(res,502,{error:'تعذر تحميل ملف الكتاب حالياً.'});return res.destroy();}}
if(req.method==='POST'&&url.pathname==='/api/ask'){const data=JSON.parse(await readBody(req)||'{}');const question=String(data.question||'').trim();if(!question)return send(res,400,{error:'السؤال فارغ.'});const text=source(data);const prompt=`أنت مساعد تعليمي لمنصة أبو شريك. أجب بالعربية فقط وبمستوى الطالب. المستوى: ${data.level||'غير محدد'}. المادة: ${data.book||'غير محددة'}. الصفحة: ${data.page||'غير محددة'}.\nالمصدر المتاح:\n${text||'[لا يوجد نص مصدر متاح]'}\nإذا توفر نص من الصفحة فاعتمد عليه أولاً. إن لم يتوفر، أجب عن السؤال الدراسي العام إن كان واضحاً، ولا تدّع أنك رأيت الصفحة.\nسؤال الطالب: ${question}\nالجواب:`;try{return send(res,200,{answer:await askAI(prompt)});}catch(e){return send(res,503,{error:friendlyError(e)});}}
if(req.method==='POST'&&url.pathname==='/api/study'){const data=JSON.parse(await readBody(req)||'{}');const text=source(data);if(text.length<80)return send(res,400,{error:'لا يوجد نص كافٍ من الكتاب لإنشاء محتوى موثوق. افتح صفحة من الدرس تحتوي مادة تعليمية ثم أعد المحاولة.'});const mode=data.mode==='mcq'?'mcq':'cards';const policy=studyPolicy(data.book);const rules=mode==='cards'?`أنشئ حتى 5 بطاقات تعليمية عالية القيمة من أهم محتوى الدرس فقط. صغ السؤال كما قد يسأله معلم أو كما يفيد الطالب في المراجعة. اجعل الجواب دقيقاً ومختصراً ومبنياً حصراً على المصدر. لا تكرر الفكرة نفسها بصيغ مختلفة. أعد JSON فقط بالشكل: {"items":[{"front":"سؤال دراسي مهم","back":"جواب دقيق من المصدر"}]}.`:`أنشئ حتى 5 أسئلة اختيار من متعدد عالية القيمة من أهم محتوى الدرس فقط. اجعل كل سؤال يقيس الفهم أو الحفظ المهم، وليس تفاصيل النشر أو شكل الصفحة. لكل سؤال 4 خيارات معقولة من نفس النوع، إجابة صحيحة واحدة فقط، وتفسير قصير مستند للمصدر. لا تجعل الإجابة الصحيحة واضحة بسبب طولها أو صياغتها. أعد JSON فقط بالشكل: {"items":[{"question":"سؤال دراسي مهم","options":["خيار 1","خيار 2","خيار 3","خيار 4"],"answer":0,"explanation":"سبب صحة الإجابة من المصدر"}]}.`;const prompt=`أنت معلم خبير ومصمم أسئلة مدرسية لمنصة أبو شريك. المستوى: ${data.level||'غير محدد'}.\n${policy}\n${rules}\n\nالمصدر الوحيد المسموح الاعتماد عليه:\n${text}`;try{const raw=await askAI(prompt,true);let parsed;try{parsed=JSON.parse(raw)}catch{return send(res,502,{error:'وصل رد من الذكاء الاصطناعي لكن تعذر قراءة JSON. حاول مرة أخرى.'});}if(!Array.isArray(parsed?.items))return send(res,502,{error:'لم يتم إنشاء محتوى دراسي صالح. حاول مرة أخرى.'});if(!parsed.items.length)return send(res,422,{error:'هذه الصفحة لا تحتوي مادة دراسية كافية لإنشاء أسئلة مفيدة. انتقل إلى صفحة من الدرس ثم جرّب مجدداً.'});return send(res,200,{items:parsed.items.slice(0,5)});}catch(e){return send(res,503,{error:friendlyError(e)});}}
if(req.method!=='GET')return send(res,405,{error:'Method not allowed'});let pathname=decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname);const safe=normalize(pathname).replace(/^[/\\]+/,'').replace(/^(\.\.(\/|\\|$))+/,'');const path=join(root,safe);if(!path.startsWith(root))return send(res,403,'Forbidden','text/plain');try{const st=await stat(path);if(!st.isFile())throw new Error();const file=await readFile(path);res.writeHead(200,{'Content-Type':types[extname(path).toLowerCase()]||'application/octet-stream','Cache-Control':'no-store, no-cache, must-revalidate'});res.end(file);}catch{return send(res,404,'Not found','text/plain');}}catch(e){console.error('[Server]',e);if(!res.headersSent)send(res,500,{error:'حدث خطأ في الخادم. حاول مرة أخرى.'});}});
server.listen(PORT,()=>console.log(`أبو شريك يعمل على المنفذ ${PORT} — Gemini ${MODEL}`));