import http from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import { extname, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';
const root=fileURLToPath(new URL('.',import.meta.url));
const PORT=Number(process.env.PORT||3000);
const GEMINI_API_KEY=process.env.GEMINI_API_KEY||'';
const MODEL=process.env.GEMINI_MODEL||'gemini-3.7-flash';
const FALLBACK_MODELS=['gemini-2.5-flash','gemini-2.5-flash-lite'];
const RELEASE_BASE='https://github.com/ahmadaljarad/abu-shreek/releases/download/books-v1/';
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.pdf':'application/pdf','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.svg':'image/svg+xml'};
function send(res,status,body,type='application/json; charset=utf-8'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store'});res.end(typeof body==='string'?body:JSON.stringify(body));}
function readBody(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>resolve(s));req.on('error',reject);});}
async function askOne(model,prompt,json=false){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),90000);try{const endpoint=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(GEMINI_API_KEY)}`;const body={contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{temperature:json?0.1:0.3,maxOutputTokens:json?1600:700,...(json?{responseMimeType:'application/json'}:{})}};const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify(body)});const raw=await r.text();let j={};try{j=JSON.parse(raw)}catch{}if(!r.ok){const e=new Error(j?.error?.message||raw||`Gemini HTTP ${r.status}`);e.status=r.status;throw e;}const answer=(j.candidates?.[0]?.content?.parts||[]).map(p=>p.text||'').join('').trim();if(!answer)throw new Error('empty response');return answer;}finally{clearTimeout(timer);}}
async function askAI(prompt,json=false){if(!GEMINI_API_KEY)throw new Error('GEMINI_API_KEY غير مضبوط.');let last;for(const model of [...new Set([MODEL,...FALLBACK_MODELS])]){try{return await askOne(model,prompt,json)}catch(e){last=e;console.warn('Gemini model failed:',model,e.message);if(e.status&&![429,500,502,503,504].includes(e.status))break;}}throw last||new Error('AI unavailable');}
function friendlyError(e){const s=String(e?.message||e||'');if(e?.name==='AbortError')return 'تأخر الذكاء الاصطناعي في الرد. حاول مرة أخرى.';if(/high demand|overloaded|resource exhausted|quota|429|503|unavailable/i.test(s))return 'خدمة الذكاء الاصطناعي مشغولة حالياً. جرّب مرة أخرى بعد قليل.';return 'تعذر الحصول على إجابة من الذكاء الاصطناعي حالياً. حاول مرة أخرى.';}
function source(data){return String(data.sourceText||data.pageText||'').trim().slice(0,18000)}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');
if(req.method==='GET'&&url.pathname==='/api/status')return send(res,GEMINI_API_KEY?200:503,{ok:!!GEMINI_API_KEY,provider:'Gemini',model:MODEL,error:GEMINI_API_KEY?undefined:'GEMINI_API_KEY غير مضبوط.'});
if(req.method==='GET'&&url.pathname==='/api/book'){const file=String(url.searchParams.get('file')||'');if(!/^[A-Za-z0-9._-]+\.pdf$/i.test(file))return send(res,400,{error:'اسم ملف الكتاب غير صالح.'});try{const upstream=await fetch(RELEASE_BASE+encodeURIComponent(file),{redirect:'follow',headers:{'User-Agent':'Abu-Shreek/1.0','Accept':'application/pdf,application/octet-stream;q=0.9,*/*;q=0.8'}});if(!upstream.ok)return send(res,upstream.status===404?404:502,{error:`تعذر تحميل الكتاب من المصدر (${upstream.status}).`});const data=Buffer.from(await upstream.arrayBuffer());res.writeHead(200,{'Content-Type':'application/pdf','Content-Length':data.length,'Cache-Control':'public, max-age=3600','Access-Control-Allow-Origin':'*'});return res.end(data);}catch(e){return send(res,502,{error:'تعذر تحميل ملف الكتاب حالياً.'});}}
if(req.method==='POST'&&url.pathname==='/api/ask'){const data=JSON.parse(await readBody(req)||'{}');const question=String(data.question||'').trim();if(!question)return send(res,400,{error:'السؤال فارغ.'});const text=source(data);const prompt=`أنت مساعد تعليمي لمنصة أبو شريك. أجب بالعربية فقط وبمستوى الطالب. المستوى: ${data.level||'غير محدد'}. المادة: ${data.book||'غير محددة'}. الصفحة: ${data.page||'غير محددة'}.\nالمصدر المتاح:\n${text||'[لا يوجد نص مصدر متاح]'}\nلا تدّع أنك قرأت شيئاً غير موجود في المصدر. إذا كان السؤال عن محتوى الصفحة ولا يكفي النص المتاح، قل بوضوح إنك تحتاج نصاً أو صورة الجزء المطلوب.\nسؤال الطالب: ${question}\nالجواب:`;try{return send(res,200,{answer:await askAI(prompt)});}catch(e){return send(res,503,{error:friendlyError(e)});}}
if(req.method==='POST'&&url.pathname==='/api/study'){const data=JSON.parse(await readBody(req)||'{}');const text=source(data);if(text.length<80)return send(res,400,{error:'لا يوجد نص كافٍ من الكتاب لإنشاء محتوى موثوق. افتح صفحات الكتاب أولاً أو أضف نص المادة.'});const mode=data.mode==='mcq'?'mcq':'cards';const rules=mode==='cards'?`أنشئ من المصدر فقط 8 بطاقات تعليمية مفيدة وغير مكررة. أعد JSON فقط بالشكل: {"items":[{"front":"سؤال قصير","back":"جواب دقيق من المصدر"}]}. لا تضف معلومات من خارج المصدر.`:`أنشئ من المصدر فقط 8 أسئلة اختيار من متعدد مفيدة وغير مكررة. لكل سؤال أربع إجابات مع إجابة صحيحة واحدة. أعد JSON فقط بالشكل: {"items":[{"question":"السؤال","options":["أ","ب","ج","د"],"answer":0,"explanation":"سبب مختصر من المصدر"}]}. غيّر موضع الإجابة الصحيحة بين الأسئلة ولا تستخدم أسئلة سطحية عن رقم الصفحة أو لون الكتاب.`;const prompt=`أنت منشئ محتوى دراسي لمنصة أبو شريك. المستوى: ${data.level||''}. المادة: ${data.book||''}.\n${rules}\nالمصدر:\n${text}`;try{const raw=await askAI(prompt,true);let parsed;try{parsed=JSON.parse(raw)}catch{return send(res,502,{error:'تعذر قراءة المحتوى المولد. حاول مرة أخرى.'});}return send(res,200,parsed);}catch(e){return send(res,503,{error:friendlyError(e)});}}
if(req.method!=='GET')return send(res,405,{error:'Method not allowed'});let pathname=decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname);const safe=normalize(pathname).replace(/^[/\\]+/,'').replace(/^(\.\.(\/|\\|$))+/,'');const path=join(root,safe);if(!path.startsWith(root))return send(res,403,'Forbidden','text/plain');try{const st=await stat(path);if(!st.isFile())throw new Error();const file=await readFile(path);res.writeHead(200,{'Content-Type':types[extname(path).toLowerCase()]||'application/octet-stream','Cache-Control':'no-store, no-cache, must-revalidate'});res.end(file);}catch{return send(res,404,'Not found','text/plain');}}catch(e){console.error('[Server]',e);send(res,500,{error:'حدث خطأ في الخادم. حاول مرة أخرى.'});}});
server.listen(PORT,()=>console.log(`أبو شريك يعمل على المنفذ ${PORT} — Gemini ${MODEL}`));