/* أبو شريك: الكتب + دراسة الصفحة الحالية + فيديوهات الدرس */
(function(){
const BOOKS={
'تاسع|اللغة العربية':'9-Arabic.pdf','تاسع|الرياضيات':'9-Algebra.pdf','تاسع|علم الأحياء والأرض':'9-Science.pdf','تاسع|الفيزياء والكيمياء':'9-Physics-Chemistry.pdf','تاسع|التاريخ':'9-History.pdf','تاسع|الجغرافيا':'9-Geography.pdf','تاسع|التربية الوطنية':'9-National.pdf','تاسع|التربية الإسلامية':'9-Islamic.pdf','تاسع|التربية المسيحية':'9-Christianity.pdf','تاسع|الفنون':'9-Art.pdf','تاسع|اللغة الإنكليزية':'9-English-SB.pdf','تاسع|اللغة الفرنسية':'9-French-SB.pdf','تاسع|اللغة الروسية':'9-Russian.pdf','تاسع|التقانة':'9-Technology.pdf','تاسع|الموسيقا':'9-Music.pdf',
'بكالوريا علمي|اللغة العربية':'bac-sci-arabic.pdf','بكالوريا علمي|الرياضيات':'bac-sci-math-1.pdf','بكالوريا علمي|الفيزياء':'bac-sci-physics.pdf','بكالوريا علمي|الكيمياء':'bac-sci-chemistry.pdf','بكالوريا علمي|علم الأحياء':'bac-sci-biology.pdf','بكالوريا علمي|اللغة الإنكليزية':'bac-sci-english-sb.pdf','بكالوريا علمي|اللغة الفرنسية':'bac-sci-french.pdf','بكالوريا علمي|اللغة الروسية':'bac-sci-russian.pdf','بكالوريا علمي|التربية الإسلامية':'bac-sci-islamic.pdf','بكالوريا علمي|التربية المسيحية':'bac-sci-christian.pdf',
'بكالوريا أدبي|اللغة العربية':'bac-lit-arabic.pdf','بكالوريا أدبي|الفلسفة':'bac-lit-philosophy-1.pdf','بكالوريا أدبي|التاريخ':'bac-lit-history.pdf','بكالوريا أدبي|الجغرافيا':'bac-lit-geography.pdf','بكالوريا أدبي|اللغة الإنكليزية':'bac-lit-english-sb.pdf','بكالوريا أدبي|اللغة الفرنسية':'bac-lit-french.pdf','بكالوريا أدبي|اللغة الروسية':'bac-lit-russian.pdf','بكالوريا أدبي|التربية الإسلامية':'bac-lit-islamic.pdf','بكالوريا أدبي|التربية المسيحية':'bac-lit-christian.pdf'};
Object.assign(bookFiles,BOOKS);
let generatedMCQ=[];
const norm=s=>String(s||'').replace(/\s+/g,' ').trim();
const isProblemSubject=()=>['الرياضيات','الفيزياء','الكيمياء','الفيزياء والكيمياء'].includes(state.subject);
const file=()=>BOOKS[`${state.level}|${state.subject}`]||bookFiles[`${state.level}|${state.subject}`]||'';
const url=f=>`/api/book?file=${encodeURIComponent(f)}`;
const pageKey=t=>key(`${t}:page:${state.page}`);
async function loadPdf(){if(state.pdf)return state.pdf;const f=file();if(!f)throw new Error('NO_BOOK');state.pdf=await pdfjsLib.getDocument({url:url(f),disableAutoFetch:true,disableStream:false,rangeChunkSize:262144}).promise;return state.pdf}
async function digitalText(n){const pdf=await loadPdf(),p=await pdf.getPage(n),t=await p.getTextContent();return norm(t.items.map(x=>x.str||'').join(' '))}
let ocrPromise=null,workerPromise=null;
function loadOCR(){if(window.Tesseract)return Promise.resolve();if(ocrPromise)return ocrPromise;ocrPromise=new Promise((ok,bad)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=ok;s.onerror=()=>bad(new Error('OCR_LOAD'));document.head.appendChild(s)});return ocrPromise}
async function worker(){await loadOCR();if(!workerPromise)workerPromise=Tesseract.createWorker('ara+eng');return workerPromise}
async function imageText(n){const ck=key(`pageText-v3-${n}`),saved=localStorage.getItem(ck);if(saved&&saved.length>60)return saved;const pdf=await loadPdf(),p=await pdf.getPage(n),v=p.getViewport({scale:1.35}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await p.render({canvasContext:c.getContext('2d',{alpha:false}),viewport:v}).promise;const w=await worker(),r=await w.recognize(c),t=norm(r?.data?.text);if(t.length>40)try{localStorage.setItem(ck,t)}catch{}return t}
async function currentText(){let t=norm(state.pageText);if(t.length>=80)return t;try{t=await digitalText(state.page||1)}catch{}if(t.length>=80)return t;return imageText(state.page||1)}
async function studySource(){let parts=[];const here=await currentText();if(here.length>=60)parts.push(`الصفحة الحالية ${state.page}: ${here}`);const pdf=await loadPdf();for(const n of [state.page+1,state.page-1]){if(n<1||n>pdf.numPages)continue;try{const t=await digitalText(n);if(t.length>=100)parts.push(`صفحة ${n}: ${t}`)}catch{}}return parts.join('\n').slice(0,7000)}

function ensureVideos(){let b=document.getElementById('lessonVideos');if(b)return b;const side=document.querySelector('#book .side');if(!side)return null;b=document.createElement('div');b.id='lessonVideos';b.style.cssText='margin-top:18px;padding-top:14px;border-top:1px solid #dce8e5';side.appendChild(b);return b}
function videoTopic(){const t=norm(state.pageText);return t.length>25?t.slice(0,130):`${state.subject} ${state.level}`}
function renderVideos(){const b=ensureVideos();if(!b)return;if(!isProblemSubject()){b.innerHTML='';return}const q=encodeURIComponent(`${state.subject} ${state.level} ${videoTopic()} شرح عربي المنهاج السوري`),q2=encodeURIComponent(`${state.subject} ${state.level} ${videoTopic()} Arabic subtitles`);b.innerHTML=`<h3>🎥 فيديوهات تشرح هذا الموضوع</h3><p class="note">مرتبطة بالمادة والصفحة الحالية، مع أولوية للشرح العربي.</p><a class="btn primary" target="_blank" rel="noopener" href="https://www.youtube.com/results?search_query=${q}">فيديوهات بالعربية</a> <a class="btn soft" target="_blank" rel="noopener" href="https://www.youtube.com/results?search_query=${q2}">مع ترجمة عربية</a>`}

/* أدوات شبيهة بتطبيقات الدراسة الحديثة لكن مخصصة للرياضيات والفيزياء والكيمياء. */
function ensureCoach(){let b=document.getElementById('scienceCoach');if(b)return b;const side=document.querySelector('#book .side');if(!side)return null;b=document.createElement('div');b.id='scienceCoach';b.style.cssText='margin-top:18px;padding-top:14px;border-top:1px solid #dce8e5';side.appendChild(b);return b}
function renderCoach(){const b=ensureCoach();if(!b)return;if(!isProblemSubject()){b.innerHTML='';return}b.innerHTML=`<h3>🧠 أدوات الدراسة</h3><p class="note">تعتمد على المادة والصفحة المفتوحة حالياً.</p><div class="actions" style="justify-content:flex-start"><button class="btn soft" onclick="scienceAction('explain')">📖 اشرح الدرس</button><button class="btn soft" onclick="scienceAction('solve')">✏️ حل التمارين</button><button class="btn soft" onclick="scienceAction('hint')">💡 أعطني تلميحاً</button><button class="btn soft" onclick="scienceAction('steps')">🧩 حل خطوة بخطوة</button><button class="btn soft" onclick="scienceAction('similar')">📝 تمرين مشابه</button><button class="btn soft" onclick="scienceAction('check')">✅ تحقق من حلي</button></div>`}
async function sendCoach(prompt){addMsg(prompt,'user');const w=document.createElement('div');w.className='msg ai';w.textContent='جارٍ قراءة الصفحة والتفكير...';chatlog.appendChild(w);try{const text=await currentText();const r=await fetch('/api/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:prompt,level:state.level,book:state.subject,page:state.page,pageText:text})});const j=await r.json();w.textContent=j.answer||j.error||'لم تصل إجابة.'}catch(e){w.textContent='تعذر قراءة الصفحة أو الاتصال بالذكاء الاصطناعي.'}}
window.scienceAction=async function(type){const custom=norm(question.value);const prompts={explain:'اشرح محتوى هذه الصفحة ببساطة، وركز على المفاهيم والقوانين والأمثلة المهمة دون الخروج عن محتواها.',solve:'استخرج التمارين أو المسائل الظاهرة في هذه الصفحة وحلها بالتدرج. اذكر رقم السؤال إن أمكن.',hint:`أعطني تلميحاً فقط دون إعطاء الحل النهائي${custom?' للسؤال التالي: '+custom:' لأهم تمرين في الصفحة الحالية'}.`,steps:`حل خطوة بخطوة مع توضيح لماذا نقوم بكل خطوة${custom?' للسؤال التالي: '+custom:' لتمرين مناسب من الصفحة الحالية'}.`,similar:'أنشئ تمريناً جديداً مشابهاً لموضوع وتمارين الصفحة الحالية، مناسباً لنفس المستوى. لا تعط الحل مباشرة؛ انتظر محاولة الطالب.',check:`تحقق من حل الطالب التالي، وحدد أين الخطأ إن وجد ثم صححه خطوة بخطوة: ${custom||'اطلب مني أولاً أن أكتب حلي في مربع السؤال.'}`};question.value='';await sendCoach(prompts[type]||prompts.explain)};

/* في المواد العلمية نستبدل البطاقات والاختيار المتعدد بأدوات حل وفهم. */
function configureModes(){const modes=document.querySelectorAll('#module .mode');if(modes.length<3)return;const cards=modes[1],mcq=modes[2];if(isProblemSubject()){
 cards.onclick=()=>openScienceMode('solve');cards.querySelector('.icon').textContent='✏️';cards.querySelector('h2').textContent='حل وتمارين';cards.querySelector('p').textContent='حل مسائل الصفحة الحالية مع شرح واضح خطوة بخطوة';const p1=cards.querySelector('.progress');if(p1)p1.style.display='none';
 mcq.onclick=()=>openScienceMode('practice');mcq.querySelector('.icon').textContent='🧠';mcq.querySelector('h2').textContent='تدريب ذكي';mcq.querySelector('p').textContent='تلميحات، تمارين مشابهة، وتصحيح حلك';const p2=mcq.querySelector('.progress');if(p2)p2.style.display='none';
 }else{
 cards.onclick=()=>openCards();cards.querySelector('.icon').textContent='🗂️';cards.querySelector('h2').textContent='البطاقات التعليمية';cards.querySelector('p').textContent='بطاقات مولدة من الدرس والصفحة الحالية فقط';const p1=cards.querySelector('.progress');if(p1)p1.style.display='block';
 mcq.onclick=()=>openMCQ();mcq.querySelector('.icon').textContent='✅';mcq.querySelector('h2').textContent='اختيار من متعدد';mcq.querySelector('p').textContent='أسئلة من الدرس والصفحة الحالية فقط';const p2=mcq.querySelector('.progress');if(p2)p2.style.display='block';}}
const originalOpenSubject=window.openSubject;
window.openSubject=function(s){originalOpenSubject(s);configureModes()};
window.openScienceMode=async function(kind){await openBook();setTimeout(()=>scienceAction(kind==='solve'?'solve':'similar'),100)};

window.openBook=async function(){show('book');chatlog.innerHTML='';pdfCanvas.style.display='block';bookHint.textContent='جارٍ تحميل الكتاب...';try{const pdf=await loadPdf();state.page=Math.max(1,Math.min(state.page||1,pdf.numPages));await renderPage()}catch(e){pdfCanvas.style.display='none';bookHint.textContent=e.message==='NO_BOOK'?'كتاب هذه المادة لم يتم ربطه بعد.':'تعذر تحميل الكتاب حالياً. حاول مرة أخرى.';console.error('[book]',e)}};
window.renderPage=async function(){if(!state.pdf)return;const p=await state.pdf.getPage(state.page),v=p.getViewport({scale:1.25}),c=pdfCanvas,x=c.getContext('2d');c.width=v.width;c.height=v.height;await p.render({canvasContext:x,viewport:v}).promise;pageLabel.textContent=`صفحة ${state.page} من ${state.pdf.numPages}`;try{state.pageText=await digitalText(state.page)}catch{state.pageText=''}bookHint.textContent='';renderCoach();renderVideos()};

if(typeof window.askAI==='function'){const originalAsk=window.askAI;window.askAI=async function(){if(!norm(state.pageText).length){try{bookHint.textContent='جارٍ قراءة الصفحة الحالية...';state.pageText=await currentText();bookHint.textContent=''}catch(e){bookHint.textContent=''}}return originalAsk()}}

/* التخزين أصبح خاصاً بالمادة + الصفحة لمنع ظهور أسئلة مادة أو صفحة أخرى. */
window.cardsForSubject=function(){try{return JSON.parse(localStorage.getItem(pageKey('generatedCards'))||'[]')}catch{return[]}};
async function generate(mode,force=false){if(isProblemSubject())throw new Error('SCIENCE_MODE');const sk=pageKey(mode==='cards'?'generatedCards':'generatedMCQ');if(!force){try{const old=JSON.parse(localStorage.getItem(sk)||'[]');if(old.length)return old}catch{}}const src=await studySource();if(src.length<80)throw new Error('NO_TEXT');const r=await fetch('/api/study',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,level:state.level,book:state.subject,page:state.page,sourceText:src})});let j={};try{j=await r.json()}catch{throw new Error('BAD_JSON')}if(!r.ok)throw new Error(j.error||'AI_ERROR');const raw=Array.isArray(j.items)?j.items:[];let out;if(mode==='cards')out=raw.map(x=>Array.isArray(x)?x:[x.front||x.question||'',x.back||x.answer||'']).filter(x=>x[0]&&x[1]);else out=raw.map(x=>({q:x.q||x.question||'',o:x.o||x.options||[],a:Number(x.answer??x.a??0),e:x.e||x.explanation||''})).filter(x=>x.q&&x.o.length===4);if(!out.length)throw new Error('EMPTY');localStorage.setItem(sk,JSON.stringify(out));return out}
function nice(e){const s=String(e?.message||e||'');if(s==='SCIENCE_MODE')return 'لهذه المادة استخدم أدوات الشرح والحل والتدريب الذكي.';if(s==='NO_TEXT')return 'لم أستطع قراءة مادة دراسية كافية من الصفحة الحالية.';if(s==='OCR_LOAD')return 'تعذر تشغيل قارئ الصفحة. تحقق من الاتصال وحاول مجدداً.';if(s==='BAD_JSON')return 'وصل رد غير صالح من الذكاء الاصطناعي. حاول مرة أخرى.';return s&&s.length<180?s:'تعذر إنشاء المحتوى حالياً. حاول مرة أخرى.'}
window.openCards=async function(){if(isProblemSubject())return openScienceMode('practice');show('cards');state.cardIndex=0;state.cardFlipped=false;flash.textContent='جارٍ قراءة الصفحة الحالية وتحضير البطاقات...';try{await generate('cards');renderCard()}catch(e){flash.textContent=nice(e);console.error('[cards]',e)}};
window.openMCQ=async function(){if(isProblemSubject())return openScienceMode('practice');show('mcq');state.mcqIndex=0;mcqQuestion.textContent='جارٍ قراءة الصفحة الحالية وتحضير الأسئلة...';mcqOptions.innerHTML='';mcqExplain.textContent='';try{generatedMCQ=await generate('mcq');nextMCQ()}catch(e){mcqQuestion.textContent=nice(e);console.error('[mcq]',e)}};
window.nextMCQ=function(){if(!generatedMCQ.length){try{generatedMCQ=JSON.parse(localStorage.getItem(pageKey('generatedMCQ'))||'[]')}catch{generatedMCQ=[]}}if(!generatedMCQ.length){mcqQuestion.textContent='لا توجد أسئلة بعد.';return}const q=state.currentMCQ=shuffledQuestion(generatedMCQ[state.mcqIndex%generatedMCQ.length]);mcqQuestion.textContent=q.q;mcqOptions.innerHTML='';mcqExplain.textContent='';q.o.forEach((o,i)=>{const b=document.createElement('button');b.className='mcq-option';b.textContent=o;b.onclick=()=>answerMCQ(i,b);mcqOptions.appendChild(b)});state.mcqIndex++;const p=progress('mcq'),n=pct(p);mcqPct.textContent=n+'%';mcqProgress.style.width=n+'%'};
window.regenerateStudy=async function(mode){localStorage.removeItem(pageKey(mode==='cards'?'generatedCards':'generatedMCQ'));if(mode==='cards'){flash.textContent='جارٍ إنشاء بطاقات جديدة...';try{await generate('cards',true);state.cardIndex=0;state.cardFlipped=false;renderCard()}catch(e){flash.textContent=nice(e)}}else{mcqQuestion.textContent='جارٍ إنشاء أسئلة جديدة...';mcqOptions.innerHTML='';try{generatedMCQ=await generate('mcq',true);state.mcqIndex=0;nextMCQ()}catch(e){mcqQuestion.textContent=nice(e)}}};
})();