/* أبو شريك: دراسة ذكية من الكتاب + قراءة مجانية للكتب المصورة */
(function(){
Object.assign(bookFiles,{
'تاسع|اللغة العربية':'9-Arabic.pdf','تاسع|الرياضيات':'9-Algebra.pdf','تاسع|علم الأحياء والأرض':'9-Science.pdf','تاسع|الفيزياء والكيمياء':'9-Physics-Chemistry.pdf','تاسع|التاريخ':'9-History.pdf','تاسع|الجغرافيا':'9-Geography.pdf','تاسع|التربية الوطنية':'9-National.pdf','تاسع|التربية الإسلامية':'9-Islamic.pdf','تاسع|التربية المسيحية':'9-Christianity.pdf','تاسع|الفنون':'9-Art.pdf','تاسع|اللغة الإنكليزية':'9-English-SB.pdf','تاسع|اللغة الفرنسية':'9-French-SB.pdf','تاسع|اللغة الروسية':'9-Russian.pdf','تاسع|التقانة':'9-Technology.pdf','تاسع|الموسيقا':'9-Music.pdf',
'بكالوريا علمي|اللغة العربية':'bac-sci-arabic.pdf','بكالوريا علمي|الرياضيات':'bac-sci-math-1.pdf','بكالوريا علمي|الفيزياء':'bac-sci-physics.pdf','بكالوريا علمي|الكيمياء':'bac-sci-chemistry.pdf','بكالوريا علمي|علم الأحياء':'bac-sci-biology.pdf','بكالوريا علمي|اللغة الإنكليزية':'bac-sci-english-sb.pdf','بكالوريا علمي|اللغة الفرنسية':'bac-sci-french.pdf','بكالوريا علمي|اللغة الروسية':'bac-sci-russian.pdf','بكالوريا علمي|التربية الإسلامية':'bac-sci-islamic.pdf','بكالوريا علمي|التربية المسيحية':'bac-sci-christian.pdf',
'بكالوريا أدبي|اللغة العربية':'bac-lit-arabic.pdf','بكالوريا أدبي|الفلسفة':'bac-lit-philosophy-1.pdf','بكالوريا أدبي|التاريخ':'bac-lit-history.pdf','بكالوريا أدبي|الجغرافيا':'bac-lit-geography.pdf','بكالوريا أدبي|اللغة الإنكليزية':'bac-lit-english-sb.pdf','بكالوريا أدبي|اللغة الفرنسية':'bac-lit-french.pdf','بكالوريا أدبي|اللغة الروسية':'bac-lit-russian.pdf','بكالوريا أدبي|التربية الإسلامية':'bac-lit-islamic.pdf','بكالوريا أدبي|التربية المسيحية':'bac-lit-christian.pdf'});
let generatedMCQ=[];
const pdfUrl=f=>'/api/book?file='+encodeURIComponent(f);
const pdfOptions=f=>({url:pdfUrl(f),withCredentials:false,disableRange:false,disableStream:false,disableAutoFetch:true,rangeChunkSize:262144});
const norm=s=>String(s||'').replace(/\s+/g,' ').trim();

function ensureVideoBox(){let box=document.getElementById('lessonVideos');if(box)return box;const side=document.querySelector('#book .side');if(!side)return null;box=document.createElement('div');box.id='lessonVideos';box.style.cssText='margin-top:18px;padding-top:14px;border-top:1px solid #dce8e5';side.appendChild(box);return box;}
function topicFromPage(){const t=norm(state.pageText);if(!t)return state.subject;const bad=/حقوق|وزارة|تأليف|الطبعة|المؤسسة|الجمهورية|الفهرس|المحتويات/g;return t.replace(bad,' ').split(' ').filter(x=>x.length>2).slice(0,14).join(' ')||state.subject;}
function renderVideoLinks(){const box=ensureVideoBox();if(!box)return;const science=['الرياضيات','الفيزياء','الكيمياء','الفيزياء والكيمياء'].includes(state.subject);if(!science){box.innerHTML='';return;}const topic=topicFromPage(),y=q=>'https://www.youtube.com/results?search_query='+encodeURIComponent(q);box.innerHTML=`<h3>🎥 فيديوهات تشرح هذا الموضوع</h3><p class="note">بحث مرتبط بالدرس الحالي، مع أولوية للشرح العربي.</p><div class="actions" style="justify-content:flex-start"><a class="btn primary" target="_blank" rel="noopener" href="${y(`${state.level} ${state.subject} ${topic} شرح عربي`)}">فيديوهات بالعربية</a><a class="btn soft" target="_blank" rel="noopener" href="${y(`${state.subject} ${topic} Arabic subtitles`)}">مع ترجمة عربية</a></div>`;}

let ocrLoader=null,ocrWorker=null;
function loadOCR(){if(window.Tesseract)return Promise.resolve();if(ocrLoader)return ocrLoader;ocrLoader=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=resolve;s.onerror=()=>reject(new Error('تعذر تحميل قارئ الصفحات المصورة. تحقق من الإنترنت وحاول مجدداً.'));document.head.appendChild(s)});return ocrLoader;}
async function getOCRWorker(){await loadOCR();if(!ocrWorker){bookHint.textContent='يتم تجهيز قارئ الصفحات المصورة لأول مرة...';ocrWorker=await Tesseract.createWorker('ara+eng',1,{logger:m=>{if(m.status==='recognizing text')bookHint.textContent=`جارٍ قراءة الصفحة المصورة... ${Math.round((m.progress||0)*100)}%`;}});}return ocrWorker;}
async function renderPageImage(pdf,n,scale=1.65){const p=await pdf.getPage(n),v=p.getViewport({scale}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await p.render({canvasContext:c.getContext('2d',{alpha:false}),viewport:v}).promise;return c;}
async function ocrPage(pdf,n){const ck=key('ocr-v1-p'+n),saved=localStorage.getItem(ck);if(saved&&saved.length>60)return saved;const worker=await getOCRWorker(),canvas=await renderPageImage(pdf,n);const r=await worker.recognize(canvas),text=norm(r?.data?.text);if(text.length>40)try{localStorage.setItem(ck,text)}catch{}return text;}
async function extractPage(pdf,n,allowOCR=false){const p=await pdf.getPage(n),tc=await p.getTextContent(),text=norm(tc.items.map(x=>x.str).join(' '));if(text.length>=100||!allowOCR)return text;return await ocrPage(pdf,n);}

window.openBook=async function(){show('book');chatlog.innerHTML='';const f=bookFiles[`${state.level}|${state.subject}`];if(!f){bookHint.textContent='كتاب هذه المادة لم يتم ربطه بعد.';return;}bookHint.textContent='جارٍ تحميل الكتاب...';try{state.pdf=await pdfjsLib.getDocument(pdfOptions(f)).promise;state.page=1;await renderPage();renderVideoLinks();}catch(e){console.error(e);bookHint.textContent='تعذر تحميل الكتاب حالياً.';}};
const oldRender=window.renderPage||renderPage;
window.renderPage=async function(){await oldRender();if(state.pdf&&norm(state.pageText).length<80){bookHint.textContent='هذه صفحة مصورة. اضغط «اقرأ الصفحة المصورة» ليقرأ أبو شريك محتواها.';let b=document.getElementById('ocrCurrent');if(!b){b=document.createElement('button');b.id='ocrCurrent';b.className='btn soft';b.style.margin='8px auto';b.textContent='📷 اقرأ الصفحة المصورة';b.onclick=async()=>{try{b.disabled=true;state.pageText=await ocrPage(state.pdf,state.page);bookHint.textContent=state.pageText?'تمت قراءة الصفحة المصورة بنجاح. يمكنك الآن سؤال أبو شريك عنها.':'لم أستطع استخراج نص واضح من هذه الصفحة.';renderVideoLinks();}catch(e){bookHint.textContent=e.message||'تعذر قراءة الصفحة.';}finally{b.disabled=false;}};document.querySelector('#book .viewer').appendChild(b);}}else{const b=document.getElementById('ocrCurrent');if(b)b.remove();}renderVideoLinks();};

function pageScore(text,n){const t=norm(text);if(t.length<100)return-100;let s=Math.min(8,t.length/320);for(const x of ['حقوق التأليف','حقوق الطبع','جميع الحقوق','وزارة التربية','المؤسسة العامة للطباعة','دار النشر','رقم الإيداع','الطبعة','لجنة التأليف','الفهرس','المحتويات'])if(t.includes(x))s-=4;for(const x of ['الدرس','الوحدة','نشاط','أتعلم','أستنتج','تمرين','مثال','تعريف','قانون','تجربة','سؤال','علل','فسر','نتيجة','سبب','مسألة'])if(t.includes(x))s+=1.5;if(n<=4)s-=3;return s;}
function scanPages(total){const set=new Set();for(let n=1;n<=Math.min(total,35);n++)set.add(n);const step=Math.max(1,Math.floor(total/45));for(let n=36;n<=total;n+=step)set.add(n);return [...set].slice(0,85);}
async function ensureBookSource(){const cacheKey=key('bookSource-v9'),cached=localStorage.getItem(cacheKey);if(cached&&cached.length>600)return cached;let pdf=state.pdf;if(!pdf){const f=bookFiles[`${state.level}|${state.subject}`];if(!f)throw new Error('كتاب هذه المادة لم يتم ربطه بعد.');pdf=await pdfjsLib.getDocument(pdfOptions(f)).promise;}const candidates=[];const near=[];if(state.page)for(let n=Math.max(1,state.page-2);n<=Math.min(pdf.numPages,state.page+3);n++)near.push(n);for(const n of near){try{const text=await extractPage(pdf,n,true),score=pageScore(text,n)+8;if(score>0)candidates.push({n,text,score});}catch(e){console.warn('[OCR]',n,e);}}
for(const n of scanPages(pdf.numPages)){if(near.includes(n))continue;try{const text=await extractPage(pdf,n,false),score=pageScore(text,n);if(score>0)candidates.push({n,text,score});}catch{}}
/* إذا كان الكتاب كله صوراً، نقرأ عدداً محدوداً من صفحات موزعة مجاناً بدلاً من OCR الكتاب كله. */
if(!candidates.length){bookHint.textContent='الكتاب مصور. جارٍ قراءة صفحات دراسية منه...';const start=Math.min(pdf.numPages,Math.max(5,state.page||5));const picks=[start,start+1,start+2,Math.round(pdf.numPages*.25),Math.round(pdf.numPages*.5),Math.round(pdf.numPages*.75)].filter((n,i,a)=>n>=1&&n<=pdf.numPages&&a.indexOf(n)===i);for(const n of picks){try{const text=await extractPage(pdf,n,true),score=pageScore(text,n)+4;if(score>0)candidates.push({n,text,score});}catch(e){console.warn('[OCR scan]',n,e);}}}
const unique=new Map();for(const c of candidates){const old=unique.get(c.n);if(!old||c.score>old.score)unique.set(c.n,c);}const chosen=[...unique.values()].sort((a,b)=>b.score-a.score).slice(0,12).sort((a,b)=>a.n-b.n);let source=chosen.map(x=>`صفحة ${x.n}: ${x.text}`).join('\n').slice(0,17500);if(source.length<300)throw new Error('لم أستطع قراءة نص دراسي كافٍ من الصفحات المصورة. افتح صفحة من الدرس ثم اضغط «اقرأ الصفحة المصورة» وحاول مجدداً.');try{localStorage.setItem(cacheKey,source)}catch{}return source;}
async function generate(mode){const sourceText=await ensureBookSource();let r;try{r=await fetch('/api/study',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,level:state.level,book:state.subject,sourceText})});}catch{throw new Error('تعذر الاتصال بخادم أبو شريك.');}let j={};try{j=await r.json()}catch{throw new Error('وصل رد غير مكتمل. حاول مرة أخرى.');}if(!r.ok)throw new Error(j.error||'تعذر إنشاء المحتوى.');if(!Array.isArray(j.items)||!j.items.length)throw new Error('لم يتم إنشاء محتوى دراسي صالح.');return j.items;}
window.openCards=async function(){show('cards');const flash=document.getElementById('flash');flash.textContent='جارٍ تحضير بطاقات '+state.subject+' من الدروس... قد تستغرق قراءة الكتاب المصور قليلاً في المرة الأولى.';try{let cards;const saved=localStorage.getItem(key('generatedCards'));if(saved)cards=JSON.parse(saved);if(!Array.isArray(cards)||!cards.length){const items=await generate('cards');cards=items.filter(x=>x&&x.front&&x.back).map(x=>[String(x.front),String(x.back)]);localStorage.setItem(key('generatedCards'),JSON.stringify(cards));}state.cardIndex=0;state.cardFlipped=false;renderCard();}catch(e){flash.textContent=e.message||'تعذر إنشاء البطاقات.';}};
window.openMCQ=async function(){show('mcq');mcqQuestion.textContent='جارٍ تحضير أسئلة '+state.subject+' من الدروس... قد تستغرق قراءة الكتاب المصور قليلاً في المرة الأولى.';mcqOptions.innerHTML='';try{let items;const saved=localStorage.getItem(key('generatedMCQ'));if(saved)items=JSON.parse(saved);if(!Array.isArray(items)||!items.length){items=await generate('mcq');localStorage.setItem(key('generatedMCQ'),JSON.stringify(items));}generatedMCQ=items.filter(x=>x&&x.question&&Array.isArray(x.options)&&x.options.length===4).map(x=>({q:String(x.question),o:x.options.map(String),a:Number(x.answer),e:String(x.explanation||'')}));state.mcqIndex=0;window.nextMCQ();}catch(e){mcqQuestion.textContent=e.message||'تعذر إنشاء الأسئلة.';}};
window.nextMCQ=function(){if(!generatedMCQ.length){mcqQuestion.textContent='لا توجد أسئلة مولدة بعد.';return;}const base=generatedMCQ[state.mcqIndex++%generatedMCQ.length],q=shuffledQuestion(base);state.currentMCQ=q;mcqQuestion.textContent=q.q;mcqExplain.textContent='';mcqOptions.innerHTML='';q.o.forEach((o,i)=>{const b=document.createElement('button');b.className='mcq-option';b.textContent=o;b.onclick=()=>answerMCQ(i,b);mcqOptions.appendChild(b)});const p=progress('mcq'),n=pct(p);mcqPct.textContent=n+'%';mcqProgress.style.width=n+'%';};
window.regenerateStudy=async function(mode){localStorage.removeItem(key(mode==='cards'?'generatedCards':'generatedMCQ'));for(const v of ['bookSource-v3','bookSource-v4','bookSource-v5','bookSource-v6','bookSource-v7','bookSource-v8','bookSource-v9'])localStorage.removeItem(key(v));return mode==='cards'?window.openCards():window.openMCQ();};
})();