/* أبو شريك - ارفع ملفك وادرسه. يظهر داخل كل مرحلة دراسية. */
(function(){
let currentFile=null,currentText='',ocrLoader=null,ocrWorker=null;
function inject(){if(document.getElementById('uploadStudy'))return;const sec=document.createElement('section');sec.id='uploadStudy';sec.className='hidden';sec.innerHTML=`<div class="topbar"><button class="btn soft" id="uploadBackLevel">← المواد</button><h2><img src="attach.svg" alt="" style="width:25px;height:25px;vertical-align:middle;margin-left:7px"> ارفع ملفك وادرسه</h2></div><div class="study"><div style="border:2px dashed #b7d8d2;border-radius:18px;padding:28px;text-align:center;background:#f8fafc"><img src="attach.svg" alt="إرفاق ملف" style="width:52px;height:52px;display:block;margin:0 auto 10px"><h3>اختر صورة أو PDF أو ملفاً نصياً</h3><p class="note">PDF، JPG، PNG، WEBP، TXT — حتى 8 MB. لا يُضاف الملف إلى كتب المنصة.</p><input id="studyFileInput" type="file" accept=".pdf,.txt,.md,image/jpeg,image/png,image/webp" style="display:none"><button class="btn primary" id="chooseStudyFile">اختيار ملف</button></div><div id="studyFileInfo" class="hidden" style="margin-top:16px;padding:14px;border:1px solid #dce8e5;border-radius:14px"></div><div id="studyFileActions" class="hidden" style="margin-top:18px"><h3>ماذا تريد من أبو شريك؟</h3><div class="actions" style="justify-content:flex-start"><button class="btn soft" data-a="explain">📖 اشرح المحتوى</button><button class="btn soft" data-a="solve">✏️ حل الأسئلة</button><button class="btn soft" data-a="summary">📝 لخّص الملف</button><button class="btn soft" data-a="cards">🗂️ بطاقات تعليمية</button><button class="btn soft" data-a="mcq">✅ اختيار من متعدد</button></div><h3 style="margin-top:20px">💬 اسأل عن الملف</h3><div class="row"><input id="fileStudyQuestion" placeholder="مثال: اشرح لي السؤال الثالث"><button class="btn primary" id="askFileButton">اسأل</button></div><div id="fileStudyOutput" class="chatlog" style="max-height:none;margin-top:16px;white-space:pre-wrap;line-height:1.9"></div></div></div>`;document.querySelector('main').appendChild(sec);const input=sec.querySelector('#studyFileInput');sec.querySelector('#chooseStudyFile').onclick=()=>input.click();sec.querySelector('#uploadBackLevel').onclick=()=>show('level');input.onchange=()=>handleFile(input.files[0]);sec.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>runAction(b.dataset.a));sec.querySelector('#askFileButton').onclick=()=>{const q=sec.querySelector('#fileStudyQuestion').value.trim();if(q)askFile(q)}}
function addLevelCard(){const box=document.getElementById('subjects');if(!box||box.querySelector('[data-upload-study]'))return;const d=document.createElement('div');d.className='subject';d.dataset.uploadStudy='1';d.innerHTML='<img src="attach.svg" alt="إرفاق ملف" style="width:42px;height:42px;display:block;margin:0 auto 8px"><b>ارفع ملفك وادرسه</b><div class="note" style="margin-top:7px">PDF أو صورة أو ملف نصي</div>';d.onclick=()=>window.openUploadStudy();box.appendChild(d)}
window.addUploadStudyToLevel=addLevelCard;
window.openUploadStudy=function(){inject();show('uploadStudy')};
function info(html,err=false){const d=document.getElementById('studyFileInfo');d.classList.remove('hidden');d.innerHTML=html;d.style.borderColor=err?'#ef4444':'#dce8e5'}
async function loadOCR(){if(window.Tesseract)return;if(!ocrLoader)ocrLoader=new Promise((ok,bad)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=ok;s.onerror=bad;document.head.appendChild(s)});await ocrLoader}
async function ocr(source){await loadOCR();if(!ocrWorker)ocrWorker=await Tesseract.createWorker('ara+eng');const r=await ocrWorker.recognize(source);return String(r?.data?.text||'').replace(/\s+/g,' ').trim()}
async function handleFile(f){if(!f)return;if(f.size>8*1024*1024)return info('الملف أكبر من 8 MB. اختر ملفاً أصغر.',true);currentFile=f;currentText='';document.getElementById('studyFileActions').classList.add('hidden');info(`جارٍ قراءة ${f.name} ...`);try{if(f.type.startsWith('image/')){info(`📷 جارٍ قراءة النص من الصورة ${f.name}...`);currentText=await ocr(f)}else if(f.type==='application/pdf'||/\.pdf$/i.test(f.name)){currentText=await pdfText(f)}else currentText=(await f.text()).slice(0,40000);if(currentText.trim().length<20)throw Error('NO_TEXT');info(`✅ ${f.name}<br><span class="note">تمت قراءة المحتوى وأصبح جاهزاً للدراسة.</span>`);document.getElementById('studyFileActions').classList.remove('hidden')}catch(e){console.error(e);info('لم أستطع قراءة محتوى الملف بوضوح. جرّب صورة أوضح أو PDF آخر.',true)}}
async function pdfText(f){if(!window.pdfjsLib)throw Error('PDF');const pdf=await pdfjsLib.getDocument({data:await f.arrayBuffer()}).promise,out=[];for(let n=1;n<=Math.min(pdf.numPages,20);n++){const p=await pdf.getPage(n),t=await p.getTextContent();let s=t.items.map(x=>x.str||'').join(' ').replace(/\s+/g,' ').trim();if(s.length<35&&n<=5){const v=p.getViewport({scale:1.4}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;s=await ocr(c)}if(s)out.push(`صفحة ${n}: ${s}`);if(out.join('\n').length>38000)break}return out.join('\n').slice(0,40000)}
function promptFor(a){return {explain:'اشرح محتوى هذا الملف للطالب بلغة عربية بسيطة ومنظمة. التزم بالمصدر فقط ولا تضف معلومات غير موجودة فيه.',solve:'استخرج الأسئلة أو التمارين الموجودة في الملف وحلها. للمسائل الحسابية اعرض الحل خطوة بخطوة والنتيجة النهائية بوضوح.',summary:'لخّص أهم محتوى الملف للمراجعة. لا تضف معلومات غير موجودة في الملف.',cards:'أنشئ بطاقات تعليمية عالية القيمة من الملف فقط. اكتب كل بطاقة بهذا الشكل: السؤال — الجواب.',mcq:'أنشئ أسئلة اختيار من متعدد اعتماداً على الملف فقط. لكل سؤال أربعة خيارات ثم الإجابة الصحيحة وتفسير قصير من المصدر.'}[a]}
async function runAction(a){return askFile(promptFor(a))}
async function askFile(q){const out=document.getElementById('fileStudyOutput');if(!currentText)return out.textContent='ارفع ملفاً قابلاً للقراءة أولاً.';out.textContent='جارٍ تحليل الملف...';try{const source=currentText.slice(0,7000);const question=`اعتمد حصراً على محتوى الملف التالي. إذا لم يدعم الملف نقطة ما فقل إنها غير موجودة فيه. اسم الملف: ${currentFile?.name||'ملف الطالب'}.\n\nمحتوى الملف:\n${source}\n\nطلب الطالب:\n${q}`;const r=await fetch('/api/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,level:'ملف الطالب',book:currentFile?.name||'ملف مرفوع',pageText:source})});const j=await r.json();out.textContent=j.answer||j.error||'لم تصل إجابة.'}catch(e){out.textContent='تعذر تحليل الملف حالياً. حاول مرة أخرى.'}}
inject();
})();